### ISSUE TITLE
when I use quanto lib to quantize the flux model, the activation layer's quantization on pipe.transformer failed

### ISSUE THREAD

**Issue by DaaadShot** [huggingface/optimum-quanto#337] opened 2024-10-15 01:52 UTC
pipe = FluxPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16).to('cuda')
quantize(pipe.text_encoder_2, weights=qfloat8, activations=qfloat8)
freeze(pipe.text_encoder_2)
quantize(pipe.transformer, weights=qfloat8, activations=qfloat8)
freeze(pipe.transformer)

and I got this error

Traceback (most recent call last):
  File "/mnt/pfs-ssai-cv/liyanqiao/ComfyUI/inference_fp8.py", line 75, in <module>
    quantize(pipe.transformer, weights=qfloat8, activations=qfloat8)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 98, in quantize
    _quantize_submodule(model, name, m, weights=weights, activations=activations, optimizer=optimizer)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/optimum/quanto/quantize.py", line 45, in _quantize_submodule
    qmodule = quantize_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 90, in quantize_module
    return qcls.from_module(module, weights=weights, activations=activations, optimizer=optimizer)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/optimum/quanto/nn/qmodule.py", line 215, in from_module
    qmodule = cls.qcreate(module, weights, activations, optimizer, device="meta")
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/optimum/quanto/nn/qlayernorm.py", line 44, in qcreate
    dtype=module.weight.dtype,
AttributeError: 'NoneType' object has no attribute 'dtype'

It seems not support the flux model's transformer's activation layer

**Comment by dacorvo** [comment] 2024-10-15 07:01
@DaaadShot thank you for reporting this issue. I am closing it as it is a duplicate of #335.

**Closed by dacorvo** 2024-10-15 07:01 UTC
Labels: duplicate
